[package]
name = "aero-online-installer"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
sha2 = "0.10"
single-instance = "0.3"
slint = "1.17.1"

[build-dependencies]
slint-build = "1.17.1"
winres = "0.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
