name: build

on:
  pull_request:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build Windows setup
        run: node scripts/ci-build-release.cjs --platform=windows

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-Windows-x64
          path: dist/release/*
          if-no-files-found: error
          retention-days: 7

  linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm ci

      - name: Install Linux Tauri dependencies
        run: sudo apt-get update --yes && sudo apt-get install --yes libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Test
        run: npm run test

      - name: Build Linux AppImage
        run: node scripts/ci-build-release.cjs --platform=linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-Linux-x64
          path: dist/release/*
          if-no-files-found: error
          retention-days: 7
